### PR TITLE
Service account login should include promotion scope

### PR DESCRIPTION
**Pull request by ashleyfrieze**
Using `frodo-lib` from another tool, the login doesn't include promotion scope, which means we can't build out the use of promotion APIs.

### CODE REVIEW

**Comment by vscheuber** [comment]
@ashleyfrieze I'll have to give this one some hard thinking. When requesting a scope not granted explicitly to the service account object, then oauth2 flow will fail:
```
% frodo info volker-dev
Service account login error: Unsupported scope for service account: fr:idc:promotion:*
%
```
If I merge the PR, ALL frodo service accounts will break and users will have to manually fix them (add the scope). Frodo could potentially try to fix it but only if connection profiles are being used and only if the connection profile contains an admin account and password, as service accounts cannot increase their own access.

So I am thinking more about only asking for the scopes required for the command being executed. Promotions weren't quite ready when frodo started to support service accounts, so I didn't ask for that scope in good old "least privilege" manner. And there will be more scopes as ID Cloud adds more features requiring distinct scopes. So this is something I have to think about carefully.

But my current thinking is to maybe add a scope param to the `getAccessTokenForServiceAccount()` method. Let me know if you have any other good ideas how not to break every existing frodo service account.

**Comment by ashleyfrieze** [comment]
@vscheuber  - I see there's been some deeper refactoring on this function, so my proposal can't be merged. However, I've proposed what I think is a workable way forward. I can rebase and make it work with your new function signature if you agree. Have a look.

**Comment by ashleyfrieze** [comment]
@vscheuber - a couple of other notes:

1. The fact that the interfaces to things like `getAccessTokenForServiceAccount` are changing, makes it a tricky decision to want to use `frodo-lib` as a consumer - you've essentially broken our tool with this change, though it's not a hard breaking change to manage
2. The way `frodo-lib` imports `package.json` from _where it knows it is on the file system_ leads to some very strange effects indeed if you try to produce a separate app based on `frodo`. It would probably be better not to do this, or at least to do it from a single place and maybe have a fallback if `package.json` isn't present.

Note: we've built a tool of our own which contains all the things frodo-lib can't do for us, some of which we'll try to submit back. The tool also orchestrates how we use frodo-lib. We're packaging it with webpack, and hit all sorts of glitches.

**Comment by vscheuber** [comment]
@ashleyfrieze the `main` branch is now hosting frodo 2.x code. The `1.x` branch holds the code you are familiar with. Yes, there are breaking changes to 1.x, but not to the methods you listed. The library structure is changing and I'm using a separate factory layer to be the library while the functions you are used to using are all internal now.

Actually, most of the the library methods have not changed at all in 2.x from a developer perspective. The library is not exposing the exported functions from each file, but is working differently to support connecting to multiple instances of ForgeRock simultaneously.

2.x is still in pre-release. Your PRs should probably go against the 1.x branch. If you join our next frodo call, we can walk you through the big changes. They should actually be minor on your side as a library user and make the library much more flexible.

I do not understand your comment regarding package.json. This is library internal and should not impact you at all. If it does, I need more details to understand the issue.

**Comment by ashleyfrieze** [comment]
@vscheuber - search for things like this:

```ts
const pkg = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8')
);
```

This expects to find `package.json` in the right place on the filesystem. While that works if you've pulled in `frodo-lib` as an npm package with associated node_modules files etc, it doesn't work if you do what we're doing, which is to webpack the whole of our deployment tool into a single .js file.

If all occurrences of this were moved into a single file `getPackageVersion` and there were a fallback, without needing to find `package.json` to do it - say an environment variable - then life would be easier.

**Comment by vscheuber** [comment]
I'll definitely look into that, @ashleyfrieze , that was an item on my list to do anyway.

**Comment by vscheuber** [comment]
I haven't forgotten about this but I will not be able to leverage this PR in the 2.x branch and I need to consider IGA scopes and the new data analytics scopes as well. Closing.

**Comment by ashleyfrieze** [comment]
@vscheuber - it's a good job we built our own promotion tool. Waiting for one to be provided would have somewhat stopped our delivery. I appreciate this is an open source project which you do on your spare time, but you need to feed back to FR/Ping that this entire approach - the tragedy of the commons - is letting customers down.

That said, I'm sure you're doing great work on Frodo, and giving a lot of your time for free, which is great...

... but you ought to be paid by your employers to merge with fr-config-manager and provide a holistic set of tools.

**Pull request closed without merging**
