### PR TITLE
Add Mocks for Test Imports

### PR DESCRIPTION
**Pull request by phalestrivir**
Adds a bunch of mocks for frodo-cli test imports, which are part of the other pull request titled "Fix Imports and Add Import Tests"  in the frodo-cli repo. Fixes a problem in journey imports as well where certain errors being thrown in a journey import test did not contain a "status" attribute.

### CODE REVIEW

**Comment by vscheuber** [comment]
Hi @phalestrivir thanks for the PR (and the ones from last week). I noticed that the new recordings in this PR still contain bearer tokens and assertions. Did you re-base your Trivir branch lately? Not too long ago I updated the pollyjs recording logic to not write bearer tokens, assertions, and basic auth creds to the har files.

**Comment by phalestrivir** [comment]
> Hi @phalestrivir thanks for the PR (and the ones from last week). I noticed that the new recordings in this PR still contain bearer tokens and assertions. Did you re-base your Trivir branch lately? Not too long ago I updated the pollyjs recording logic to not write bearer tokens, assertions, and basic auth creds to the har files.

Hi @vscheuber, yes, I did rebase the branch I was working on to have your changes. However, I didn't realize that you had made changes to the pollyjs recording logic. Some of the mocks in this pull request were created before those changes (I have been working on these tests on and off the past couple weeks since I'm not working full-time at the moment), so as a result I noticed some of the older mocks do still have the bearer tokens and assertions while the newer mocks do not.  I can go ahead and update all the older mocks, although I won't have time to do it until tomorrow. Would you prefer I make a commit to amend this PR with the updated mocks, or should I close this pull request and make a new one that doesn't include the old mocks in the commit history?

**Comment by vscheuber** [comment]
@phalestrivir ah! no worries, if the recordings are old, we can just leave them. I find that some of the tests don't work for me when I run them on my desktop or in the pipeline because they are executing parallel and then I just regenerate the recordings and snapshots while I solve the issue. So all is well, just wanted to make sure we are not pushing valid tokens to the repo, even if it's only for a few minutes until they expire.

**Comment by phalestrivir** [comment]
> @phalestrivir ah! no worries, if the recordings are old, we can just leave them. I find that some of the tests don't work for me when I run them on my desktop or in the pipeline because they are executing parallel and then I just regenerate the recordings and snapshots while I solve the issue. So all is well, just wanted to make sure we are not pushing valid tokens to the repo, even if it's only for a few minutes until they expire.

@vscheuber Ok, sounds good! Let me know if you have other questions or if there's anything else I can do.

**Pull request merged**
