### PR TITLE
Switch to tsup with imported json

### PR DESCRIPTION
**Pull request by ashleyfrieze**
@vscheuber - this is a deeper change

- Upgrade Node to v18
- Change build completely from babel to tsup
- Import all json files in the "production" code. I note that the `MockForgeRockApi` still uses `import.meta.env` and `readFileSync` and I'm ignoring that
- Modify the build in the pipeline

I'm not sure how precisely to test that the new package is fit for consumers. This may be something that you know better how to test. However, I think this version of the code should operate a lot better for packaging in binary with FrodoCLI.

We should also note that the typescript code comes up with a lot of "compile" errors - things which really don't follow the prescribed types. This isn't something I've introduced, but represents general risks around the code. Worth looking at longer-term.

### CODE REVIEW

**Comment by vscheuber** [comment]
@ashleyfrieze , thank you so much for this PR! @hfranklin and his team are working on the bundling. tsup looks really promising but I believe they are going down the esbuild path.

**Comment by ashleyfrieze** [comment]
@vscheuber - I agreed to do this with @hfranklin on the last call. `tsup` is a superset of `esbuild` and I firmly believe this approach will work really well with the `frodo cli` changes.

**Comment by ashleyfrieze** [comment]
Hey @hfranklin - please go ahead and do it the way you'd prefer to. If it works for you, then I'm delighted.

My next step will be to try to bump axios when this is done. Hopefully the work I did has been helpful!

**Comment by hfranklin** [comment]
@ashleyfrieze It was very helpful. I split into two changes so we can complete the import meta changes before changing the build.

**Comment by vscheuber** [comment]
merged with additional changes in pr/405 (#412). Thank you, @ashleyfrieze, for getting us on the right track! Your PR was extremely helpful!

**Pull request closed without merging**
