### PR TITLE
Fix and Improve Imports and Exports

### PR DESCRIPTION
**Pull request by phalestrivir**
This PR makes some fixes and improvements to Frodo imports and exports. This PR is part of a bigger PR that adds additional imports/exports into Frodo, but due to the amount of bug fixes and other miscellaneous changes I made I decided to separate them into separate PRs. Once this one is merged, I will create the other PR that contains the new additional imports and exports.

Note that a corresponding PR in Frodo-CLI under the same name as this PR relies on the changes in this PR.

The list of changes include:
- Updated test timeouts from 90000 to 120000 milliseconds (to accommodate the bigger exports/imports in the future)
- Updated resource versions of different exports/imports to the latest ones
- Updated comments and type information to be more accurate and fix typos
- Fixed TrustedJWTIssuer exports/imports (since these will be included as part of the full config export/import in the future PR)
- Fixed service imports to work for federation services
- Updated exports for agents and esv secrets/variables to have a singular instead of plural type (i.e. agents => agent, secrets => secret, variables => variable). The reason for this is to make them more consistent with the rest of the exports which are also singular, and also because secrets plural will be used for exporting AM secret config in the future PR with additional exports/imports.
- For full exports, duplicate config is now deleted from the IDM exports since themes, email templates, and mappings are all handled separately.
- Fixed full imports to only import if the full import config contains the items being imported rather than erroring out.
- Fixed full imports to return the config items that were imported
- Fixed email template imports/exports. For exports, there was a bug with the api where not all email templates were being exported using “emailTemplate” as the type, but it was fixed by using “emailTemplat” as the type instead (not sure why this works, but it’s the best solution I could find to fix the problem).
- Moved functionality for handling env substitution and entity filters from CLI to lib for IDM exports/imports.
- Fixed a few bugs with importing/exporting journeys. The main issue that was found was that if you were importing a journey containing nodes that are not supported by the current deployment (e.g. IDM journey nodes from cloud being imported into a classic deployment of AM), the journey would still be imported. This would cause an error to be thrown on export of the journey preventing it as well as other journeys from being exported on full export. The fix here was to just prevent the import of the journey if this happens by erroring out to prevent those errors from happening on export.
- Fixed a few bugs with script imports to allow each of the 3 types of imports to work (i.e. if scripts are a single unencoded string, if scripts are a single encoded string, and if scripts are a decoded array). 
- Fixed an issue with file paths on the Windows version of Frodo that were causing errors on imports due to the differences between Windows and Linux file paths.

### CODE REVIEW

**Comment by vscheuber** [comment]
@phalestrivir @hfranklin the PR looks great! Nice work! I have only started to review in detail but will complete asap.

One thing that jumped the eye and worries me is: A lot of API version updates across the board in many API layer modules. I am not sure which AM versions we will drop support for by doing this? I have stuck to the versions the UI was using at the time I was initially implementing most modules and I have not updated the version in any modules as far as I can remember.

So this also raises the question if we have to take a stance and either narrow our support window or dynamically pick a version based on the platform versions we detect. I just don't know how much complexity we can handle if we were to go down that path. Probably better to narrow our window and say: 7.x is supported, not below. But with all the changes in this PR I don't even know if that was true?

I will reach out internally to find a good way to establish which API versions for which API are supported in which AM version, so we can decide which one we want to base Frodo on. What do y'all think?

**Comment by phalestrivir** [comment]
> @phalestrivir @hfranklin the PR looks great! Nice work! I have only started to review in detail but will complete asap.
> 
> One thing that jumped the eye and worries me is: A lot of API version updates across the board in many API layer modules. I am not sure which AM versions we will drop support for by doing this? I have stuck to the versions the UI was using at the time I was initially implementing most modules and I have not updated the version in any modules as far as I can remember.
> 
> So this also raises the question if we have to take a stance and either narrow our support window or dynamically pick a version based on the platform versions we detect. I just don't know how much complexity we can handle if we were to go down that path. Probably better to narrow our window and say: 7.x is supported, not below. But with all the changes in this PR I don't even know if that was true?
> 
> I will reach out internally to find a good way to establish which API versions for which API are supported in which AM version, so we can decide which one we want to base Frodo on. What do y'all think?

@vscheuber @hfranklin That's a good point, I wasn't thinking of supporting previous versions. I think that would make sense to support 7.x and not below. I got the API versions by web scraping the Amster documentation for the latest 7.5.0 version, so if we want to support 7.5 and above this would work, otherwise I could scrape the 7.0.0 documentation and update the PR with those API versions so that it supports all 7.x versions if we want to go that route

**Comment by vscheuber** [comment]
Thinking about this some more, what if we made the API version values an array with the latest version being the top value. Our API layer will always use the top value but If we receive an error, we will fall back to the next etc. Not a fully formulated plan, yet, but just throwing around some ideas how we can maintain support for older versions. And maybe we do something like a global API version index where we have the same number of versions in each array across all modules, even if the values are the same. Then as the first API call fails and we find a version header that works for that API, we update the global index in state with that array index and from that moment on, every module falls back to that level and we can avoid every module failing independently and wasting a lot of time with the falling back.

I do believe your change was great, @phalestrivir and we need to keep up with the new versions, but I do not want to lose backwards compatibility because of it.

What if we did something like this in every API layer module:
```javascript
const apiVersion = [
  'protocol=3.0,resource=1.0',
  'protocol=2.1,resource=1.0',
  'protocol=2.1,resource=1.0',
  'protocol=2.0,resource=1.0'
];
```

And then when frodo launches, we start with global index 0 and on error we go to index 1, 2, 3, etc. 
```javascript
const getNodeApiConfig = () => {
  return {
    apiVersion[state.getApiVersionIndex()],
  };
};
```

Something along those lines. Then in a new global test we would make sure that the length of every apiVersion array anywhere in the library is the same.

**Comment by vscheuber** [comment]
Of course, thinking about this some more, we'd have to have the array in ascending order so that the meaning of an index does not change. So we would have oldest top, then newer versions after that:
```javascript
const apiVersion = [
  'protocol=2.0,resource=1.0',
  'protocol=2.1,resource=1.0',
  'protocol=2.1,resource=1.0',
  'protocol=3.0,resource=1.0'
];
```

**Comment by vscheuber** [comment]
it appears that unsupported protocol versions return a 400:

**Comment by vscheuber** [comment]
Alright, in our call this morning we decided: To update this PR to remove all the API header version updates and get the PR merged asap. Then address the versions immediately after.

We think that for cloud we should keep using the latest versions where necessary and for self-hosted we should fallback to older versions. We are thinking of having only one fallback version (oldest functional version) and the latest version. Cloud deployments always use latest and should always work. Forgeops and classic deployments attempt to use latest and on failure will use fallback version.

**Comment by phalestrivir** [comment]
I reverted the changes to the resource/protocol versions. Tests are still passing in both the lib and the CLI on my machine, so it should be ready to go to be merged in.

**Pull request merged**
